version: '3.8'

services:
  # API Application Service
  api:
    build: .
    container_name: film_api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DIALECT=mysql
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - IMGUR_CLIENT_ID=${IMGUR_CLIENT_ID}
    volumes:
      - ./uploads:/app/uploads
      - ./user-database-film-movie-pmo-firebase-adminsdk-fbsvc-ce92bbb9e3.json:/app/user-database-film-movie-pmo-firebase-adminsdk-fbsvc-ce92bbb9e3.json:ro
    network_mode: "host"