version: '3.8'

services:
  # API Application Service
  api:
    build: .
    container_name: film_api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DIALECT=mysql
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000
      # Firebase configuration
      # - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      # - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      # - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      # Email configuration
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      # Google Drive API
      # - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      # - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      # - GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}
      # Imgur API
      - IMGUR_CLIENT_ID=${IMGUR_CLIENT_ID}
    volumes:
      - ./uploads:/app/uploads
      - ./user-database-film-movie-pmo-firebase-adminsdk-fbsvc-ce92bbb9e3.json:/app/user-database-film-movie-pmo-firebase-adminsdk-fbsvc-ce92bbb9e3.json:ro
    network_mode: "host"