services:
  app-api-film:
    build: .
    container_name: api-database-film
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    restart: unless-stopped